clear all;
close all;
colormap winter

% Load in audio files that were generated by the audio splitter
location = fullfile("DatasetGenerator",'SplitAudioFiles');
ads = audioDatastore(location,'IncludeSubFolders',true,...
    'LabelSource','foldernames');

% % % Log out result to check load worked correctly
countEachLabel(ads)

% % % % % % Partition Data into 80% 20% split for now
rng(100)
ads = shuffle(ads);
[adsTrain,adsTest] = splitEachLabel(ads,0.8);

% % % % % % Log out splits to check it has worked as intended
countEachLabel(adsTrain)
countEachLabel(adsTest)

