COMPUTER_ID = "testbedtwo"
SESSION_NAME = "21-12-2021_12:33:13"
FILE_NAME = "Test Bed 2.wav"
SECRET = "REPLACE_WITH_FIREBASE_SECRET_WHEN_DEPLOYED"
OUTPUTCSVNAME = "CSVNAMEYOUWANTTOCREATE.csv"
KEYLOGGER_START_OFFSET_IN_MS = 160.890