import pandas as pd
from glob import glob
import matplotlib.pyplot as plt
import numpy as np
from config import OUTPUTCSVNAME

# File takes in csv file created from featureExtractor and creates a histogram of data

# Load csv generated by DatasetGenerator directory
data = pd.read_csv('./DataSets/' + OUTPUTCSVNAME)



# Get Label Column
y = data.iloc[:, 20].values


categories = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
              "T", "U", "V", "W", "X", "Y", "Z", "Space", ",", "Backspace", "'", "-", "Enter", "FullStop", "1!", "2", "3", "4", "5", "6", "7", "8", "9"]


values = []

for category in categories:
    count = np.count_nonzero(y == category)
    values.append(count)


# Plot histogram
plt.style.use('ggplot')
y_pos = np.arange(len(categories))

plt.bar(y_pos, values, align='center', alpha=0.5)
plt.xticks(y_pos, categories, rotation="90")
plt.ylabel('Frequency')
plt.title('Letter Distribution in Dataset')

plt.show()
